import test from'node:test';import assert from'node:assert/strict';import{createApp}from'../server/app.mjs';import{readConfig}from'../server/security.mjs';
async function withApp(run,extras={}){const cfg={...readConfig({}),...extras};const{server}=await createApp(cfg,{epoch:'test-epoch',...extras.options});await new Promise(r=>server.listen(0,'127.0.0.1',r));const port=server.address().port;cfg.origin=`http://127.0.0.1:${port}`;cfg.host=`127.0.0.1:${port}`;const request=(path,init={})=>fetch(cfg.origin+path,init);try{await run(request,cfg);}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
test('serves the mobile shell and normalized demo snapshot',()=>withApp(async request=>{const shell=await request('/');assert.equal(shell.status,200);assert.match(await shell.text(),/YOUR NEXT INSTRUCTION/);const s=await(await request('/api/snapshot')).json();assert.equal(s.mode,'demo');assert.equal(s.capabilities.liveWrites,false);assert.equal(s.panes.length,5);}));
test('does not expose server source, env files, arbitrary paths, or arbitrary module files',()=>withApp(async request=>{for(const p of ['/.env','/server/security.mjs','/docs/blueprint.md','/../../etc/passwd'])assert.equal((await request(p)).status,404,p);}));
test('forbidden Origin cannot read snapshots',()=>withApp(async request=>assert.equal((await request('/api/snapshot',{headers:{Origin:'https://evil.example'}})).status,403)));
test('missing CSRF protection rejects prompt submissions',()=>withApp(async request=>assert.equal((await request('/api/prompt',{method:'POST',body:'{}'})).status,403)));
test('demo send is explicitly simulated and duplicate-safe',()=>withApp(async(request,cfg)=>{const s=await(await request('/api/snapshot')).json();const p=s.panes[0];const op={id:'http-operation-123',target:{hostId:s.host.id,epoch:s.epoch,terminalId:p.terminalId,paneId:p.paneId,sessionId:p.sessionId},text:'Hallo\n🦊'};const send=()=>request('/api/prompt',{method:'POST',headers:{'Content-Type':'application/json',Origin:cfg.origin,'X-Herdr-Mobile':'1'},body:JSON.stringify(op)});const a=await(await send()).json();const b=await(await send()).json();assert.deepEqual(a,b);assert.equal(a.status,'simulated');assert.equal(a.submittedToAgent,false);}));
test('stale target cannot submit even a demo prompt',()=>withApp(async(request,cfg)=>{const response=await request('/api/prompt',{method:'POST',headers:{'Content-Type':'application/json',Origin:cfg.origin,'X-Herdr-Mobile':'1'},body:JSON.stringify({id:'stale-operation',text:'Do it',target:{epoch:'old'}})});assert.equal(response.status,409);}));
test('real mode always rejects prompt mutation',()=>withApp(async(request,cfg)=>{const response=await request('/api/prompt',{method:'POST',headers:{Origin:cfg.origin,'X-Herdr-Mobile':'1'},body:'{}'});assert.equal(response.status,501);assert.equal((await response.json()).error,'live_control_not_implemented');},{mode:'herdr-readonly',options:{herdr:{snapshot(){throw new Error('must not be called');},close(){}}}}));
test('transcription requires explicit cloud consent',()=>withApp(async(request,cfg)=>{const response=await request('/api/transcribe',{method:'POST',headers:{Origin:cfg.origin,'X-Herdr-Mobile':'1','Content-Type':'audio/webm'},body:'audio'});assert.equal(response.status,400);assert.equal((await response.json()).error,'voice_consent_required');}));
test('security headers prevent caching output and framing',()=>withApp(async request=>{const r=await request('/api/snapshot');assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(r.headers.get('X-Frame-Options'),'DENY');assert.match(r.headers.get('Content-Security-Policy'),/connect-src 'self'/);}));
