import test from 'node:test';import assert from 'node:assert/strict';
import { titleFor,cleanText,draftKey,appendTranscript,guardTarget,validOperation,isFresh,isSnapshot,MAX_DRAFT } from '../shared/model.mjs';
import {demoSnapshot}from'../server/demo.mjs';import{readConfig}from'../server/security.mjs';
const snapshot=()=>demoSnapshot(readConfig({}),'epoch-1');
test('explicit labels win over native and terminal titles',()=>{assert.equal(titleFor({name:'My name',nativeTitle:'Native title',title:'Metadata'}),'My name');assert.equal(titleFor({label:'Pane label',title:'Metadata'}),'Pane label');});
test('normalizes display-only control characters',()=>assert.equal(cleanText('  hello\n\u001bworld  '),'hello world'));
test('missing title has a useful Windows directory fallback',()=>assert.equal(titleFor({agent:'Codex',cwd:'C:\\Code\\herdr'}),'Codex · herdr'));
test('draft keys isolate machines and sessions in the same repository',()=>{const p=snapshot().panes[0];assert.notEqual(draftKey('desktop','one',p),draftKey('laptop','one',p));assert.notEqual(draftKey('desktop','one',p),draftKey('desktop','one',{...p,sessionId:'other'}));});
test('known native-session drafts survive companion restarts',()=>{const p=snapshot().panes[0];assert.equal(draftKey('desktop','one',p),draftKey('desktop','two',p));});
test('unknown-session drafts are isolated across companion epochs',()=>{const p={...snapshot().panes[0],sessionId:''};assert.notEqual(draftKey('desktop','one',p),draftKey('desktop','two',p));});
test('transcription appends with a matching draft revision',()=>assert.deepEqual(appendTranscript({text:'Hello',revision:2},2,'Wörld 🐑'),{kind:'applied',draft:{text:'Hello\nWörld 🐑',revision:3}}));
test('late transcription cannot overwrite new typing',()=>{const d={text:'New typing',revision:3};const r=appendTranscript(d,2,'late');assert.equal(r.kind,'conflict');assert.equal(r.draft,d);assert.equal(d.text,'New typing');});
test('oversized combined transcripts are retained as a conflict, not truncated',()=>assert.equal(appendTranscript({text:'x'.repeat(MAX_DRAFT),revision:0},0,'more').kind,'too-long'));
test('empty transcripts never clear an existing draft',()=>assert.equal(appendTranscript({text:'Keep',revision:1},1,' ').kind,'empty'));
test('target validation checks host, epoch, pane, and native identity',()=>{const s=snapshot(),p=s.panes[0];const t={hostId:s.host.id,epoch:s.epoch,terminalId:p.terminalId,paneId:p.paneId,sessionId:p.sessionId};assert.equal(guardTarget(s,t),p);for(const patch of [{hostId:'wrong'},{epoch:'old'},{terminalId:'x'},{paneId:'reused'},{sessionId:'replacement'}])assert.throws(()=>guardTarget(s,{...t,...patch}),/stale_target/);});
test('shell panes cannot receive agent prompts',()=>{const s=snapshot(),p=s.panes.at(-1);assert.throws(()=>guardTarget(s,{hostId:s.host.id,epoch:s.epoch,terminalId:p.terminalId,paneId:p.paneId,sessionId:''}),/stale_target/);});
test('valid operation accepts multiline Unicode but rejects oversized/empty input',()=>{const op={id:'operation-123',text:'Hallo\näöü 🐑',target:{}};assert.ok(validOperation(op));assert.ok(!validOperation({...op,text:' '}));assert.ok(!validOperation({...op,text:'x'.repeat(MAX_DRAFT+1)}));});
test('stale and disconnected states never count as fresh',()=>{const s=snapshot();assert.ok(isFresh(s));assert.ok(!isFresh({...s,connected:false}));assert.ok(!isFresh({...s,observedAt:Date.now()-16000}));});
test('browser snapshot validation rejects unexpected shapes',()=>{const s=snapshot();assert.ok(isSnapshot(s));assert.ok(!isSnapshot({...s,panes:[{title:'bad'}]}));assert.ok(!isSnapshot({...s,schemaVersion:999}));});
